export const randomLyricsArray = [
  "Even though it took a while Good things take time You weren't there when I needed you most You let me down like for the twentieth time, now I know That you're not gonna be the somebody To carry me when I feel so weak You weren't there when I needed you most And I, I've been getting on with life And I feel happy when you're off my mind Oh, baby Even though it took a while to let you go And my heart still don't feel right, but now I know Good things take time, and oh Good things take time And I've been working on myself, on myself And I don't need nobody else, -body else, uh-oh Even though it took a while, and now I know Good things take time Things are better now that I moved on, I feel lighter I depended on you for too long, now I know that I'm yhe somebody to care for me and it feels so free Things are better now that you are gone Oh, baby Even though it took a while to let you go And my heart still don't feel right, but now I know Good things take time, and oh Good things take time And I've been working on myself, on myself And I don't need nobody else, -body else, uh-oh Even though it took a while, and now I know Good things take time For myself, for myself Ah-ooh-ooh For myself, for myself Ah-ooh-ooh For myself, for myself Good things take time And oh Even though it took a while to let you go And my heart still don't feel right, but now I know Good things take time, and oh Good things take time",
  "Sure I know I haven't been around I've been away way too long I don't know your bruises Or where you've been lately But I know I still love you I don't know where you go on Friday nights I don't know your current favorite song But I know that how I drive, it drives you crazy And I know I still love you I still love you I still want you Get to know me once more, baby With all your issues I still miss you Haven't met one like you, baby I don't know where you see yourself in 20 years I don't know if you still smoke weed, you probably do But I know that all my cussing drives you crazy And I know I still love you I still love you I still want you Get to know me once more, baby With all your issues I still miss you Haven't met one like you, baby I still love you I still want you Get to know me once more, baby With all your issues I still miss you Haven't met one like you, baby",
  "Two-hundred days and counting I know You're my favorite still When I say I won't tell myself I don't but I always will Feel the way I feel You have time to heal, I got time to kill Play in my mind like I rehearsed it I know I should re-purpose Ain't no faking hurt like this nah You carry her and all I carry are burdens Time for me ain't working I know heartbreak ain't perfect but Is it fair that you moved on 'Cause I swear that I haven't Is it right that you've grown And I'm still stuck in habits 'Cause I'm finding it strange That you're better than average Hearts didn't break down the middle Tell me how did that happen",
  "Blame it on the fact that I was so naive I put the pain inside your heart Can't fix the past with just an apology But it's still a real good place to start",
  "If I sing but don't have love I waste my breath with every song I bring an empty voice, a hollow noise If I speak with a silver tongue Convince a crowd but don't have love I leave a bitter taste with every word I say",
  "SONG LYRICS Ooh…A duck! An elephant. Hey, a rooster. I hear a cat. That’s a pig. A dog! Listen. Listen. What do you hear? I hear a dog, dog, dog, dog, dog. I hear a dog.",
  "Stomp like elephants. Let’s go to the zoo. And stomp like the elephants do. Let’s go to the zoo. And stomp like the elephants do. Jump like kangaroos. Let’s go to the zoo. And jump like the kangaroos do. Let’s go to the zoo. And jump like the kangaroos do.",
  "Let’s take a walk in the jungle. Walking in the jungle. Walking in the jungle. We’re not afraid. We’re not afraid. Walking in the jungle. Walking in the jungle. We’re not afraid. We’re not afraid. One step. Two steps. Three steps forward. One step. Two steps. Three steps back. Stop. Listen. What’s that? It’s a frog! We’re not afraid!",
  "See you later, alligator. After a while, crocodile. Bye bye, butterfly. See you again next time. See you later, alligator. After a while, crocodile. Bye bye, butterfly. See you again next time. See you again next time.",
  "Good morning. Good morning. Good morning to you. Good morning, Mr. Rooster. Cock-a-doodle-doo. Good morning. Good morning. Good morning to you. Good morning, Mr. Rooster. Cock-a-doodle-doo.",
];
